"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pytex.py']
DATA_FILES = []
OPTIONS = {
    "includes" : ["sympy"],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={
        'py2app' : {
            "includes" : ["sympy"],
        }
    },
    setup_requires=['py2app', 'sympy'],
)
